import React, { useEffect, useRef, useState } from "react";
import PageHeader from "../../../common/pageheader/pageheader";
import { api } from "../../../../resources/api";
import Loader from "../../../common/loader/loader";
import { showAlert } from "../../../common/sweetalert/sweetalert";
import { toast } from "react-toastify";
import { connect } from "react-redux";
import SearchSelect from "../../../common/select/SearchSelect";
import { formatDateAndTime } from "../../../../resources/constants";
import { useReactToPrint } from 'react-to-print';
import Barcode from "react-hooks-barcode";
import Box from "@mui/material/Box";
import LinearProgressWithLabel from "../../../common/linear-progress-bar/linear-progress-bar";
import AGTable from "../../../common/table/AGTable";

function ExamBarcode(props) {
    const [isLoading, setIsLoading] = useState(false);
    const [loading, setLoading] = useState(false);
    const [showProgress, setShowProgress] = useState(false);
    const [showProgress2, setShowProgress2] = useState(false);
    const [showProgress3, setShowProgress3] = useState(false);
    const [showBody, setshowBody] = useState(false);
    const [isFormLoading, setIsFormLoading] = useState('off');
    const [semesterList, setSemesterList] = useState([]);
    let [studentData, setStudentData] = useState([]);
    const [progress, setProgress] = useState(0);
    const [studentList, setStudentList] = useState([]);
    const [moduleList, setModuleList] = useState([]);
    const [selectedModules, setSelectedModules] = useState([]);
    const componentRef = useRef();
    const [printValue, setPrintValue] = useState('');
    const [semesterOptions, setSemesterOptions] = useState([]);
    const [showForm, setshowBarcode] = useState(false);
    const [formData, setFormData] = useState({ StudentID: "", SemesterCode: "", SemesterCode2: "", SemesterCode3: "", ModuleCode: "", ModuleCode2: "", InsertedBy: `${props.loginData[0].StaffID}` });
    const [createSchedule, setcreateSchedule] = useState({ SemesterCode: "", SemesterCode2: "" });
    const [generalDatatable, setGeneralDatatable] = useState({ columns: [{ label: "S/N", field: "sn" }, { label: "print", field: "action" }, { label: "Exam Hall", field: "HallName" }, { label: "Seat No", field: "SeatNo" }, { label: "Student ID", field: "StudentID" }, { label: "Student Name", field: "StudentName" }, { label: "Module Code ", field: "ModuleCode" }, { label: "Module Name ", field: "ModuleName" }, { label: "Attendance", field: "IsPresent" }, { label: "Generated By", field: "StaffName" }, { label: "Date Generated", field: "InsertedDate" }], rows: [] });

    const getData = async () => {
        const [semRes, studRes, modRes] = await Promise.all([
            api.get("staff/timetable/timetable/semester"),
            api.get("staff/student-manager/student/active"),
            api.get("staff/academics/module/list")
        ]);
        if (semRes.success && semRes.data?.length > 0) {
            let rows = []; let row_set = [];
            semRes.data.forEach(item => { rows.push({ value: item.SemesterCode, label: item.SemesterName }); row_set.push({ value: item.SemesterCode, label: item.SemesterName + "- " + item.SemesterCode }); });
            setSemesterList(rows); setSemesterOptions(row_set);
        }
        if (studRes.success && studRes.data?.length > 0) {
            let rows = [];
            studRes.data.forEach(item => { rows.push({ value: item.StudentID, label: `${item.FirstName} ${item.MiddleName} ${item.Surname} (${item.StudentID})` }); });
            setStudentList(rows);
        }
        if (modRes.success && modRes.data?.length > 0) {
            let rows = [];
            modRes.data.forEach(item => { rows.push({ value: item.ModuleCode, label: `${item.ModuleName} (${item.ModuleCode})` }); });
            setModuleList(rows);
        }
        setIsLoading(false);
    };

    const printBarcode = useReactToPrint({ content: () => componentRef.current });

    const getGeneralData = async (semester) => {
        setLoading(true);
        const { success, data } = await api.get(`staff/timetable/exam/barcode/list/${semester}`);
        if (success && data?.length > 0) {
            let rows = [];
            data.forEach((item, index) => {
                studentData.push(item.StudentID);
                rows.push({ sn: index + 1, action: (<button type="button" className="btn btn-sm btn-primary" onClick={() => { setPrintValue(item.Barcode); setshowBarcode(true); setTimeout(() => { printBarcode(); setshowBarcode(false); }, 100); }}><i className="fa fa-print" /></button>), HallName: item.HallName, SeatNo: item.SeatNo, StudentID: item.StudentID, StudentName: item.StudentName, ModuleCode: item.ModuleCode, ModuleName: item.ModuleName, IsPresent: item.IsPresent === 1 ? 'Attended' : 'Not Attended', StaffName: item.StaffName, InsertedDate: formatDateAndTime(item.InsertedDate, 'date') });
            });
            setGeneralDatatable({ ...generalDatatable, columns: generalDatatable.columns, rows: rows });
        } else { setGeneralDatatable({ ...generalDatatable, columns: generalDatatable.columns, rows: [] }); toast.error("No record found"); }
        setLoading(false); setshowBody(true);
    };

    const handleSelectChange = (id, selected) => {
        if (id === "ModuleCode") { const values = selected ? selected.map(op => op.value) : []; setSelectedModules(values); }
        else { setFormData({ ...formData, [id]: selected?.value || "" }); }
    };

    const onSubmit = async () => {
        if (formData.SemesterCode.trim() === "") { showAlert("EMPTY FIELD", "Please select the semester code", "error"); return false; }
        setIsFormLoading('on'); setProgress(0); setShowProgress(true);
        let sendData = { ...formData, StudentData: studentData };
        const { success, data } = await api.post("staff/timetable/exam/barcode", sendData);
        if (success) {
            setProgress(100);
            let duplicate = data.duplicate;
            if (data.message === "success") { toast.success("Exam Barcode Generated Successfully"); showAlert("BARCODE GENERATED", `Barcode Generated Successfully! \n   ${duplicate.length > 0 ? ` However, barcode has been generated for the following student(s).: ${duplicate}` : ""}  `, "success"); getGeneralData(createSchedule.SemesterCode); }
            else if (data.message === "duplicate") { showAlert("DUPLICATE ENTRIES", `Barcode has been generated for the following student(s), Please check and try again!  \n   ${duplicate.length > 0 ? ` ${duplicate}` : ""}  `, "error"); }
            else if (data.message === "empty") { showAlert("ERROR", "No exam timetable schedule for the selected semester!", "error"); }
            else { showAlert("ERROR", "Something went wrong. Please try again!", "error"); }
        } else { console.log("NETWORK ERROR"); }
    };

    const onModuleSubmit = async () => {
        if (formData.SemesterCode2.trim() === "") { showAlert("EMPTY FIELD", "Please select the semester", "error"); return false; }
        if (selectedModules.length < 1) { showAlert("EMPTY FIELD", "Please select at least 1 module", "error"); return false; }
        setIsFormLoading('on'); setProgress(0); setShowProgress2(true);
        let sendData = { ...formData, StudentData: studentData, ModuleCode: selectedModules };
        const { success, data } = await api.post("staff/timetable/exam/barcode/module", sendData);
        if (success) {
            setProgress(100);
            let duplicate = data.duplicate; let empty = data.empty_module;
            if (data.message === "success") { toast.success("Exam Barcode Generated Successfully"); showAlert("BARCODE GENERATED", `Barcode Generated Successfully! \n   ${duplicate.length > 0 ? ` However, barcode has been generated for the following student(s).: ${duplicate}` : ""} \n\n\n   ${empty.length > 0 ? ` Also, No exam timetable schedule for the following module(s): ${empty}` : ""}   `, "success"); getGeneralData(createSchedule.SemesterCode); }
            else if (data.message === "duplicate") { showAlert("DUPLICATE ENTRIES", `Barcode has been generated for the following student(s), Please check and try again!  \n   ${duplicate.length > 0 ? ` ${duplicate}` : ""}  `, "error"); }
            else if (data.message === "empty") { showAlert("ERROR", "No exam timetable schedule for the selected semester and module!", "error"); }
            else { showAlert("ERROR", "Something went wrong. Please try again!", "error"); }
        } else { console.log("NETWORK ERROR"); }
    };

    const onSemesterChange = async (e) => { if (e.value !== "") { setcreateSchedule({ ...createSchedule, SemesterCode: e.value, SemesterCode2: e }); getGeneralData(e.value); } else { setcreateSchedule({ ...createSchedule, SemesterCode: "", SemesterCode2: "" }); setshowBody(false); } };

    const onStudentSubmit = async () => {
        if (formData.SemesterCode3.trim() === "") { showAlert("EMPTY FIELD", "Please select the semester", "error"); return false; }
        if (formData.ModuleCode2.trim() === "") { showAlert("EMPTY FIELD", "Please select the module", "error"); return false; }
        if (formData.StudentID.trim() === "") { showAlert("EMPTY FIELD", "Please select the student", "error"); return false; }
        setIsFormLoading('on'); setProgress(0); setShowProgress3(true);
        let sendData = { ...formData, StudentData: studentData };
        const { success, data } = await api.post("staff/timetable/exam/barcode/student", sendData);
        if (success) {
            setProgress(100);
            let duplicate = data.duplicate;
            if (data.message === "success") { toast.success("Exam Barcode Generated Successfully"); showAlert("BARCODE GENERATED", `Barcode Generated Successfully! \n   ${duplicate.length > 0 ? ` However, barcode has been generated for the following student(s).: ${duplicate}` : ""}  `, "success"); getGeneralData(createSchedule.SemesterCode); }
            else if (data.message === "duplicate") { showAlert("DUPLICATE ENTRIES", `barcode has been generated for the following student(s), Please check and try again!  \n   ${duplicate.length > 0 ? ` ${duplicate}` : ""}  `, "error"); }
            else if (data.message === "empty") { showAlert("ERROR", "No exam timetable schedule for the selected semester, module and student!", "error"); }
            else { showAlert("ERROR", "Something went wrong. Please try again!", "error"); }
        } else { console.log("NETWORK ERROR"); }
    };

    useEffect(() => { getData(); }, []);

    return (isLoading ? <Loader /> :
        <div className="d-flex flex-column flex-row-fluid">
            <PageHeader title={"Exam Barcode"} items={["Assessment", "Exam", "Exam Barcode"]} />
            <div className="flex-column-fluid">
                {semesterOptions.length > 0 && <div className="col-md-12 mb-4"><SearchSelect id="_Semester" label="Select Semester" value={createSchedule.SemesterCode2} onChange={onSemesterChange} options={semesterOptions} placeholder="select Semester" /></div>}
                {loading ? <div className="card-body pt-7" style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100%', marginLeft: 'auto', marginRight: 'auto' }}><Loader /></div> : showBody === true &&
                    <div className="card"><div className="card-body">
                        {showForm && <div className="col-md-12 m-5 pt-5" id="exam_barcode" ref={componentRef} style={{ textAlign: 'center' }}><Barcode value={printValue} className="mt-5 pt-5" /></div>}
                        <ul className="nav nav-custom nav-tabs nav-line-tabs nav-line-tabs-2x border-0 fs-4 fw-bold mb-8"><li className="nav-item"><a className="nav-link text-active-primary pb-4 active" data-bs-toggle="tab" href="#semester">General</a></li><li className="nav-item"><a className="nav-link text-active-primary pb-4" data-kt-countup-tabs="true" data-bs-toggle="tab" href="#module">Module</a></li><li className="nav-item"><a className="nav-link text-active-primary pb-4" data-bs-toggle="tab" href="#student">Student</a></li></ul>
                        <div className="tab-content" id="myTabContent">
                            <div className="tab-pane fade active show" id="semester" role="tabpanel"><div className="d-flex col-md-12"><div className="col-md-11 form-group"><SearchSelect id="SemesterCode" value={semesterList.find(op => op.value === formData.SemesterCode) || null} options={semesterList} onChange={(selected) => handleSelectChange('SemesterCode', selected)} placeholder="Search Semester" /></div><div><button className="btn btn-light btn-active-light-primary fw-bolder flex-shrink-0" onClick={onSubmit} style={{ marginLeft: '10px' }}>Generate</button></div></div>{showProgress ? <Box sx={{ width: '100%', marginTop: '20px' }}><LinearProgressWithLabel value={progress} /></Box> : <></>}<AGTable data={generalDatatable} /></div>
                            <div className="tab-pane fade" id="module" role="tabpanel"><div className={"row"}><div className="col-md-5 mb-4"><SearchSelect id="SemesterCode2" label="Semester" value={semesterList.find(op => op.value === formData.SemesterCode2) || null} options={semesterList} onChange={(selected) => handleSelectChange('SemesterCode2', selected)} placeholder="Search Semester" /></div><div className="col-md-5 mb-4"><SearchSelect id="ModuleCode" label="Module" value={moduleList.filter(op => selectedModules.includes(op.value))} options={moduleList} isMulti onChange={(selected) => handleSelectChange('ModuleCode', selected)} placeholder="Search Module" /></div><div className="form-group col-md-2 pt-6"><button onClick={onModuleSubmit} className="btn btn-primary w-100">Generate</button></div></div>{showProgress2 ? <Box sx={{ width: '100%', marginTop: '20px' }}><LinearProgressWithLabel value={progress} /></Box> : <></>}<AGTable data={generalDatatable} /></div>
                            <div className="tab-pane fade" id="student" role="tabpanel"><div className={"row"}><div className="col-md-3 mb-4"><SearchSelect id="SemesterCode3" label="Semester" value={semesterList.find(op => op.value === formData.SemesterCode3) || null} options={semesterList} onChange={(selected) => handleSelectChange('SemesterCode3', selected)} placeholder="Search Semester" /></div><div className="col-md-3 mb-4"><SearchSelect id="ModuleCode2" label="Module" value={moduleList.find(op => op.value === formData.ModuleCode2) || null} options={moduleList} onChange={(selected) => handleSelectChange('ModuleCode2', selected)} placeholder="Search Module" /></div><div className="col-md-3 mb-4"><SearchSelect id="StudentID" label="Student" value={studentList.find(op => op.value === formData.StudentID) || null} options={studentList} onChange={(selected) => handleSelectChange('StudentID', selected)} placeholder="Search Student" /></div><div className="form-group col-md-3 pt-6"><button onClick={onStudentSubmit} className="btn btn-primary w-100">Generate</button></div></div>{showProgress3 ? <Box sx={{ width: '100%', marginTop: '20px' }}><LinearProgressWithLabel value={progress} /></Box> : <></>}<AGTable data={generalDatatable} /></div>
                        </div>
                    </div><div className="card-header border-0 pt-6"><div className="card-title" /><div className="card-toolbar"></div></div><div className="card-body pt-7" style={{ display: 'block', marginLeft: 'auto', marginRight: 'auto' }}>{isLoading ? <Loader /> : ""}</div></div>}
            </div>
        </div>
    );
}

const mapStateToProps = (state) => { return { loginData: state.LoginDetails }; };
export default connect(mapStateToProps, null)(ExamBarcode);
